language: node_js

node_js:
- "stable"

sudo: false

script:
  - cd lib
  - npm install
  - npm run lint
  - npm run build
  - rm -rf node_modules

  - cd ../example
  - npm install
  - npm run lint
  - npm run test
