language: node_js

node_js:
- "stable"

sudo: false

jobs:
  include:
  - stage: lib
    script:
      - cd lib
      - npm install
      - npm run lint
      - npm run build
      - cd example
      - npm install
      - npm run lint
      - npm run test
      - npm run build
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
      local_dir: example/dist
      on:
        branch: master
